services:
  calendarsync:
    image: registry.cn-hangzhou.aliyuncs.com/xinbaojian/calendar:latest
    container_name: calendarsync
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./config.toml:/app/config.toml:ro
    environment:
      - TZ=Asia/Shanghai
    mem_limit: 100m
